# Generated by Django 4.2.4 on 2023-08-07 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapp', '0002_remove_distanceadditionalprice_enable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distanceadditionalprice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='distancebaseprice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='timemultiplicationfactor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='waitingcharges',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='distanceadditionalprice',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='distanceadditionalprice',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='distancebaseprice',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='distancebaseprice',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='distancebaseprice',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
